# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AzAuthProxy < Formula
  desc "Local dev proxy that emulates Azure App Service Managed Identity for containers"
  homepage "https://github.com/thepsadmin/az-auth-proxy"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThePSAdmin/az-auth-proxy/releases/download/v1.0.1/az-auth-proxy_1.0.1_darwin_amd64.tar.gz"
      sha256 "85338f2ec15c7218c38ba82304c580042bddbf0e0ef6011237f88516cefba787"

      def install
        bin.install "az-auth-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThePSAdmin/az-auth-proxy/releases/download/v1.0.1/az-auth-proxy_1.0.1_darwin_arm64.tar.gz"
      sha256 "c762a15eb8e8b9380dd6ebf63a5c82a78481a27995835fc09b0878c6f6c96a83"

      def install
        bin.install "az-auth-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/az-auth-proxy/releases/download/v1.0.1/az-auth-proxy_1.0.1_linux_amd64.tar.gz"
      sha256 "7527acc5cd4fc951090ca5e8b64c6a34254b79c839a0887033700127eaebc89e"
      def install
        bin.install "az-auth-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/az-auth-proxy/releases/download/v1.0.1/az-auth-proxy_1.0.1_linux_arm64.tar.gz"
      sha256 "4830c0f39af2462cc5dde90f7fb82ee6a364892ebb9c9427c62499616405de87"
      def install
        bin.install "az-auth-proxy"
      end
    end
  end

  test do
    system "#{bin}/az-auth-proxy", "healthcheck"
  end
end
