# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mathemcli < Formula
  desc "CLI for Mathem.se grocery shopping"
  homepage "https://github.com/thepsadmin/mathemcli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThePSAdmin/mathemcli/releases/download/v1.0.3/mathemcli_1.0.3_darwin_amd64.tar.gz"
      sha256 "bc678315c8634ae894a28b67db4e30d13853f4a26dd1c5e2e0e8da217d37d0e1"

      def install
        bin.install "mathemcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThePSAdmin/mathemcli/releases/download/v1.0.3/mathemcli_1.0.3_darwin_arm64.tar.gz"
      sha256 "b51c72d2cdd1af64eaba282b16bc2269b15bec695dd77c4a3bfbfe6d1c0b06e8"

      def install
        bin.install "mathemcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/mathemcli/releases/download/v1.0.3/mathemcli_1.0.3_linux_amd64.tar.gz"
      sha256 "fc3781739cb8201a3ed6bf89b1b0a740c5d0abc4e361e6b7fc6e6fd5bc1d727b"
      def install
        bin.install "mathemcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/mathemcli/releases/download/v1.0.3/mathemcli_1.0.3_linux_arm64.tar.gz"
      sha256 "170744725130fa1946c467afdd7fe538c299cc49e2aa8293c5e71106e481582c"
      def install
        bin.install "mathemcli"
      end
    end
  end

  test do
    system "#{bin}/mathemcli", "version"
  end
end
