# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TasknotesCli < Formula
  desc "CLI for managing TaskNotes tasks in an Obsidian vault"
  homepage "https://github.com/thepsadmin/tasknotes-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThePSAdmin/tasknotes-cli/releases/download/v1.0.1/tasknotes-cli_1.0.1_darwin_amd64.tar.gz"
      sha256 "7b5e8551cdae0abbde6860e012b28dba7e4edd07347dae0532593c8069d99123"

      define_method(:install) do
        bin.install "tasknotes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThePSAdmin/tasknotes-cli/releases/download/v1.0.1/tasknotes-cli_1.0.1_darwin_arm64.tar.gz"
      sha256 "1210f0635d44a303eb4fcf5438cda8d139297a738f9929709836813f834e226f"

      define_method(:install) do
        bin.install "tasknotes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/tasknotes-cli/releases/download/v1.0.1/tasknotes-cli_1.0.1_linux_amd64.tar.gz"
      sha256 "fc4d24913032592fa8a99932018b95691fff13cf5f6055e6e363f87c1d2b8fe3"
      define_method(:install) do
        bin.install "tasknotes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThePSAdmin/tasknotes-cli/releases/download/v1.0.1/tasknotes-cli_1.0.1_linux_arm64.tar.gz"
      sha256 "41248a1f1bb4f0a075f5dccbaf2473bcc5e0f039f9a0db87350eff221fee7b2e"
      define_method(:install) do
        bin.install "tasknotes"
      end
    end
  end

  test do
    system "#{bin}/tasknotes", "version"
  end
end
